># codeclimate.yml

version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
    config:
      threshold: 50
  method-lines:
    enabled: true
    config:
      threshold: 30
plugins:
  fixme:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-60

exclude_patterns:
  - "*.*"
  - ".*"

  - Gemfile
  - LICENSE
  - Rakefile

  - benchmark/
  - docs/
  - exe/
  - features/
  - rake/
  - rubocop/
  - script/
  - spec/
  - test/
  - vendor/

  - lib/blank_template/
  - lib/site_template/
  - lib/theme_template/
  - lib/jekyll/mime.types
  - lib/jekyll/commands/serve/livereload_assets/livereload.js
  
  >### editorconfig
  root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

>### config-variables

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

Gem::Specification.new do |spec|
  spec.name          = 'jekyll-config-variables'
  spec.version       = '0.1.1'
  spec.authors       = ['9-g']
  spec.email         = ['g9@g--9.gq']
  spec.summary       = 'A Jekyll monkey-patch to allow you to use variables within your _config.yml file'
  spec.description   = ''
  spec.homepage      = 'https://github.com/9-g/jekyll-config-variables'
  spec.license       = 'MIT'

  spec.files         = `git ls-files`.split($/)
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test)/})
  spec.require_paths = ['lib']

  spec.add_runtime_dependency 'jekyll', '>= 2.0'

  spec.add_development_dependency 'bundler', '~> 1.3'
  spec.add_development_dependency 'rake'
  spec.add_development_dependency 'rspec'
end
