name: Tagging

on:
  push:
    branches: [ release ]

jobs:
  tagging:
    runs-on: ubuntu-latest
    name: Release tagging
    
    steps:
      - uses: actions/checkout@v2
        
      - run: bash scripts/tag.sh
        env:
          DEPLOY_KEY_PASSWORD: ${{ secrets.DEPLOY_KEY_PASSWORD }}